### ISSUE TITLE
Channel Export/Import via Web UI seems broken/disabled

### ISSUE THREAD

**Issue by K1WIZ** [meshtastic/web#109]
I have two meshtastic nodes running v2.1.5 and it seems the ability to export a configured channel set does not work. Attempt to copy shows is disabled.  When provisioning multiple nodes after flashing, having this available would be incredibly handy.  

On the newly flashed node, connected by serial using the web UI I go to CHannels, then import and will not accept the import link. Clicking the Submit button to finish the import on the new node does nothing.

**Comment by guillochon** [comment]
I'm not sure if the same thing exactly is being described above, but the copy button on the share channels page of the web UI (see below) does not work. I have to select the text manually then copy it with control + c.

![image](https://github.com/meshtastic/web/assets/4998058/526cb3c4-cc00-494b-bb39-d0bdced55209)
