### ISSUE TITLE
Spiffs filesystem plugin delete button not working

### ISSUE THREAD

**Issue by cyberlink1** [meshtastic/web#11]
I noticed this when I tried to delete the rangetest.csv clicking on the trashcan does nothing.

**Comment by cyberlink1** [comment]
looks like the upload button is not working as well.

**Comment by sachaw** [comment]
New filesystem browser is slowly being worked on, please update to the latest version.

**Comment by pipedogtotherescue** [comment]
Does the latest tbeam firmware cover the filesystem browser UI?  (I assume so).  I am running fw 1.2.55.9db7c62 - just installed the latest a few days ago when I got my tbeam in the mail.  Here is what the web browser looks like - clicking on the rangetest file just downloads the latest copy of the file.  I don't even see a trashcan icon.  Using edge as chrome browser can't seem to run meshweb.
![image](https://user-images.githubusercontent.com/47480568/154844650-36e1b73e-ca37-4db4-839c-da573916c299.png)

**Comment by sachaw** [comment]
@pipedogtotherescue The trash can icon that's mentioned was from an older version from the UI,
As for not working in edge, could you please tell me what version of edge you are using, as there shouldn't be any issues.

**Comment by pipedogtotherescue** [comment]
@sachaw ahh ok, good to know.  I am using Edge version 98.0.1108.56 -- it seems to work great.  The only thing that doesn't work is deleting rangetest, but seems to be a known bug.  Chrome browser doesn't work at all for me, but just noticed I am out of date and updating now.
