### ISSUE TITLE
[BUG]: Canned Message Module Missing Toggle

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/web#114]
The Canned Message module is missing the toggle to enable the module. 
<img width="829" alt="Screenshot 2023-07-11 at 7 56 58 AM" src="https://github.com/meshtastic/web/assets/6912600/5b90b8d3-b0a9-4385-812f-fa89cb5fe4c0">

**Comment by sachaw** [comment]
Fixed

**Comment by rcarteraz** [comment]
> Fixed

Oops forgot to link my PR to this issue because I forgot about this issue 😂. Thanks!
