### ISSUE TITLE
[BUG] Client uses depreciated `hasWifi` to allow network config

### ISSUE THREAD

**Issue by pdxlocations** [meshtastic/web#117]
A full wipe and install of FW version 2.1.16 or higher removes the hasWifi field which no longer allows network configuration in the web client.

This field was depreciated in [protobufs #355](https://github.com/meshtastic/protobufs/pull/355)
It is used in [DeviceConfig.tsx](https://github.com/meshtastic/web/blob/a988acd992e31aaabc12793989007484ab998e48/src/pages/Config/DeviceConfig.tsx#L37)

thebentern says "The HasX hardware capability bools can be sourced from Device Metadata now"

**Comment by RandMental** [comment]
What does this mean - that the Wifi option is now also permanently depreciated,  or only the MAC address issue?

**Comment by rcarteraz** [comment]
> What does this mean - that the Wifi option is now also permanetly depreciated, or only the MAC address issue?

No, it's not deprecated, the field that is being used by the web client is. It needs to be updated to source the information from the device metadata.
