### ISSUE TITLE
[BUG] App config tab renders module config

### ISSUE THREAD

**Issue by tobymurray** [meshtastic/web#119]
Meshtastic: 2.1.17.7ca2e81
Hardware: TTGO 1.1
Browser: Firefox 114.0.2

Web app is hosted on TTGO

Clicking on the "App Config" tab shows the Module config. Clicking on any of the items in the menu shows the corresponding Module Config. E.g. App Config > Interface actually renders Module Config > MQTT etc.

[Screencast from 2023-07-16 12:43:52 PM.webm](https://github.com/meshtastic/web/assets/3683198/a80ea100-3e51-46d2-8e92-c6d4c7abe857)

**Comment by rcarteraz** [comment]
> Meshtastic: 2.1.17.7ca2e81 Hardware: TTGO 1.1 Browser: Firefox 114.0.2
> 
> Clicking on the "App Config" tab shows the Module config. Clicking on any of the items in the menu shows the corresponding Module Config. E.g. App Config > Interface actually renders Module Config > MQTT etc.
> 
>  Screencast.from.2023-07-16.12.43.52.PM.webm

Is this local, on the device itself or at client.meshtastic.org? That's a pretty old version of the web client. If you're hosting locally, you need to update your web repo, if it's on the device itself you need to update your firmware, and if it's at client.meshtastic.org then you likely need to clear cache, content, cookies etc.

**Comment by tobymurray** [comment]
This is hosted on the device itself.
> if it's on the device itself you need to update your firmware

The device is running 2.1.17.7ca2e81 - I just updated it today. The device appears to believe it updated successfully, I'm not sure how else to validate that. Is there a separate means of updating the web app the device serves?

**Comment by rcarteraz** [comment]
> This is hosted on the device itself.
> 
> > if it's on the device itself you need to update your firmware
> 
> The device is running 2.1.17.7ca2e81 - I just updated it today. The device appears to believe it updated successfully, I'm not sure how else to validate that. Is there a separate means of updating the web app the device serves?

I would try doing a wipe/install then. The firmware version of the client matches the hosted version. Below is a screenshot of mine on a device running 2.1.17
<img width="1476" alt="Screenshot 2023-07-16 at 11 12 54 AM" src="https://github.com/meshtastic/web/assets/6912600/ad14a3fa-173f-4b6c-a4cb-f89db7a44b63">
<img width="902" alt="Screenshot 2023-07-16 at 11 13 47 AM" src="https://github.com/meshtastic/web/assets/6912600/4c7d088c-85d3-413b-8a8e-da5ca2cdee37">

**Comment by tobymurray** [comment]
Looks like that was the issue - maybe a bad update somewhere along the line such that the device reported running the latest firmware but the web app was outdated. Not sure if it was corrupt or just not implemented yet, but the old UI also didn't show the SHA so :shrug: when it was from

Re-flashed (with the installation, not the update), re-configured and I see a UI that matches yours. Thanks for the help!
