### ISSUE TITLE
Web App - New connection via WiFi don't allow a TLS to be disabled     

### ISSUE THREAD

**Issue by RandMental** [meshtastic/web#121]
Creating a new connection to a Mestatic device over WIFI don't allow non-secure connections
    
The **Use TLS** slide button cannot be move to non secure or off
 
![TLS WIFI problem](https://github.com/meshtastic/web/assets/6272455/8663e781-26b9-4027-927b-573f27004345)

**Comment by rcarteraz** [comment]
If you're using https://client.meshtastic.org then it's required.

**Comment by garthvh** [comment]
Only meshtastic.local is available via http

**Comment by RandMental** [comment]
Thanks
