### ISSUE TITLE
[Bug]: Nothing happens after clicking ‘Connect’ on the device-served website 

### ISSUE THREAD

**Issue by h0lad** [meshtastic/web#124]
### Category

Other

### Hardware

T-Beam V1.1

Tested with 433 and 868 variant

### Firmware Version

v2.2.0.9f6584b

### Description

I just Web-flashed the latest 2.2.0.9f6584b Alpha onto my T-Beam (433 and 868MHz variant). After pressing the ‘Connect’ button on the website served by the device nothing happens.

A full device erase was done. Also cleaning out all browser caches. Browser logs (Developer mode) showing no error/warning. Tested with Firefox and Chrome.

Last known working version was V2.1.21 or V2.1.20.

Just tested the Android App against the IP - connects without problems.

Is there some known issue?

Thank you!

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/nothing-happens-after-clicking-connect-on-the-device-served-website-2-2-0-9f6584b-alpha-t-beam/8005/3

**Comment by h0lad** [comment]
I bisect'ed this twice and always ended up here:

```
1012167c893d5ced7540b59acea8a0bff654bf34 is the first bad commit
commit 1012167c893d5ced7540b59acea8a0bff654bf34
Author: Sacha Weatherstone <sachaw100@hotmail.com>
Date:   Sun Jul 9 14:14:49 2023 +1000

    Second round of formatting
```

**Comment by ajmcquilkin** [comment]
Just to clarify, does this issue happen on one connection method specifically? I'm on protos `v2.0.0 alpha` and I'm seeing this when trying to connect to a TBeam over USB Serial. Looks like it could be an issue with the JS library.

![image](https://github.com/meshtastic/web/assets/46639306/d075d595-eb0f-4049-962c-2e846d941428)

**Comment by h0lad** [comment]
I only tested using the IP.

On the forum this issue was confirmed.

One person suggested a workaround: Marking the IP-Field then hitting enter. Works for me.

**Comment by rcarteraz** [comment]
> I only tested using the IP.
> 
> On the forum this issues now way confirmed this.
> 
> One person suggested a workaround: Marking the IP-Field then hitting enter. Works for me.

I can confirm this as well.

**Comment by daniel-hofer** [comment]
> > I only tested using the IP.
> > On the forum this issues now way confirmed this.
> > One person suggested a workaround: Marking the IP-Field then hitting enter. Works for me.
> 
> I can confirm this as well.

I can confirm this too, the workaround did it for me.
