### ISSUE TITLE
[Bug]: Firmware 2.2.1 Web-View empty (Browser)

### ISSUE THREAD

**Issue by daniel-hofer** [meshtastic/web#127]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.2.1

### Description

Since the update/reinstall with v.2.2.1 the maps view via serial or IP-connection is empty.
[debug2.1.1.txt](https://github.com/meshtastic/firmware/files/12356475/debug2.1.1.txt)

**Comment by daniel-hofer** [comment]
![web211](https://github.com/meshtastic/firmware/assets/7782550/f2a627c0-1f51-4cbe-82c6-4723ea071c78)

**Comment by daniel-hofer** [comment]
Bug persists with 2.2.6
index-0e7e3601.js:125 TypeError: Cannot read properties of undefined (reading 'Map')

**Comment by pdxlocations** [comment]
@daniel-hofer give this one a try with 2.2.10.
