### ISSUE TITLE
Build adjustments

### ISSUE THREAD

**Issue by qjayjayp** [meshtastic/web#131]
Hi, I'm with Meshtastic for two weeks now and it's a really cool project, I was just a disappointed by the map not working and just two days ago found there have been changes to make it work again. So I tried building the site artifacts (and after some config and install orgy the building process worked) but I got an error saying basically that the 'anchor' attribute does not exist, so as I'm really not anywhere near react, nodejs and all that stuff I found that the import statement from the api reference (https://visgl.github.io/react-map-gl/docs/api-reference/marker) looks a bit different, so I changed it from 

import { Layer, Map as Marker, Source, useMap } from "react-map-gl";
to
import { Layer, Marker, Source, useMap } from "react-map-gl";

which made the build succeed and the markers showing up (I tried with uncommenting the 'anchor', but markers where not visible). So if that would be a fix to a common problem (and not unique to my setup), which needs to be judged by someone with more insight, it may be applied generally.

**Comment by pdxlocations** [comment]
Hey, nice work.  I can confirm this fixed the map in my local build as well!
