### ISSUE TITLE
bug in night-vision of Node display.

### ISSUE THREAD

**Issue by costonisp** [meshtastic/web#14]
Browser: chrome 
OS: Linux mint19.3
Device fw-version: 1.2.50
 
Nodes that are displayed as a blue point on the map can show details when clicked.
In normal vision, it shows the name+ID in black text on a little white popup window.
In nightvision the name+ID is in white text but the popup window is still white, should probably be dark grey or black. So it is unreadable in nightvision. When the text is selected with a mouse I see the white characters in a green background.

**Comment by cyberlink1** [comment]
(Im just another user not a dev)

The latest version of the web interface has changed how that works so it opens a window on the right side of the page. You may want to try updating the interface. You can do it by going to http://<meshtastic-ip>/admin and clicking on the "Manage Web Content" then update.
Hope this helps

**Comment by sachaw** [comment]
This has undergone many changes and more are planned, closing this.
