### ISSUE TITLE
Easy install, and run? 

### ISSUE THREAD

**Issue by ghost** [meshtastic/web#144]
hello.

normal person here with (almost) zero programation experience. 
i am wondering if it would be possible to compile? or make it into a simple "click and go" type of software?
currently it seems the user need to go into command line, install a couple of programming language and stuff, then try to build the software and start it. i didnt even manage to run this myself...

i think being able to use a PC as a meshtastic handler/client is very important.
people are spending thousands of hours designing standalone meshtastic nodes, laptop PCI cards, and modules. 
being potentially able to use just about any computer, connect to a node and use it would be very good.

it would be great if the user installation would be simplified.

Thank you for your time.

**Comment by OishiiCha** [comment]
Hi, the easiest way to do it would be via Docker.

First install docker (docker desktop for mac and windows)

Then run the following for the current version to date.
```
docker run -d -p 8080:8080 -p 8443:8443 --restart always --name Meshtastic-Web ghcr.io/meshtastic/web:8288b8c4fb42386b9e072773dc05a429b4527e58
```

Hopefully that helps.

**Comment by ghost** [comment]
@OishiiCha  Thank you very much for your help! i will try this in the following days.
basically it make a "backup" of the site to run locally?

**Comment by OishiiCha** [comment]
@Miaoucat0 The devs have precompiled a docker version of the current site so if there are any updates to the site that you would like, you will have to run a new docker container.

**Comment by ghost** [comment]
@OishiiCha  alright! thank you very much for your help.
i havent tried it yet, but is docker able to run the site Backup offline after the initial setup? that would be my main goal.

**Comment by OishiiCha** [comment]
Yes it will run without the use of internet, however I am yet to get the Bluetooth and serial to work, however Lan connections should work

**Comment by OishiiCha** [comment]
Just an update, was able to get serial and bluetooth to work, there are different versions ARM or X86: 
![Screenshot 2023-11-22 at 18 38 54](https://github.com/meshtastic/web/assets/86476845/7d639aaa-fe7d-4319-9844-3d8b4644e4c4)

**Comment by ghost** [comment]
@OishiiCha  OK! thank you for much for your help!

**Comment by marek22k** [comment]
How can you save the chat history (if this is even possible) with Docker?

**Comment by OishiiCha** [comment]
> How can you save the chat history (if this is even possible) with Docker?

I don't think you can save the chats on the web version (could be wrong), when you refresh the page it will clear the device off, so the device is only connected in the frontend, there is a repo for a desktop app, but there hasn't been recent development since September, if you are familiar in coding with Rust then you can give it a go. I haven't had it successfully use serial on that desktop app yet: https://github.com/meshtastic/network-management-client.
I did try making a deb file of it, but couldn't get it to work properly yet.

**Comment by sachaw** [comment]
Instructions now in readme
