### ISSUE TITLE
Peers list - sorting not working

### ISSUE THREAD

**Issue by stylesuxx** [meshtastic/web#146]
The peers list table has carets in the column headings, indicating that it should be possible to sort by those fields, which does not seem to be the case. It would be nice if we were able to at least sort by `name` and `last heared`.

**Comment by tekstrand** [comment]
@sachaw I came across this the other day and wanted to check with you on using `react-table` or something similar to solve. Any thoughts? https://www.npmjs.com/package/react-table

**Comment by sachaw** [comment]
We're planning some pretty big changes, still a ways off though. Feel free to open any PR's

**Comment by tekstrand** [comment]
@sachaw where is that planning happening? Would enjoy being part of that.

**Comment by sachaw** [comment]
Still in the planning phase. We're looking to use a WASM plugin system. With plugins likely written in rust. Frontend will likely move to SolidJS. If you're interested, DM me on discord.
