### ISSUE TITLE
[bug]: Invalid value in the `X-Protobuf-Schema` HTTP header

### ISSUE THREAD

**Issue by ghost** [meshtastic/web#154]
The `X-Protobuf-Schema` HTTP header returned in the `/api/v1` calls (like `GET /api/v1/fromradio`, `PUT /api/v1/toradio` etc.) is invalid. 

Meshtastic returns URL which does not exist (anymore?):
```
X-Protobuf-Schema: https://raw.githubusercontent.com/meshtastic/protobufs/master/mesh.proto
```

The correct one is
```
X-Protobuf-Schema: https://raw.githubusercontent.com/meshtastic/protobufs/master/meshtastic/mesh.proto
```

**Comment by KomelT** [comment]
This was fixed in meshtastic/firmware#4411
