### ISSUE TITLE
Web client will not allow decimals for  adc_multiplier_override

### ISSUE THREAD

**Issue by mattriney** [meshtastic/web#155]
EDIT: I neglected to add details about my setup

Heltec V3
Meshtastic 2.2.17

I tried setting this value from mulitple browsers(Chrome, Firefox, etc.)

I tested this separately with the python cli and it works properly there. The web client simply does not allow decimal values to be entered. Whole numbers seem to work, but not decimal values.

**Comment by then3rd** [comment]
Confirmed. Came here to report this as well, thank you!
