### ISSUE TITLE
Node Map using web browser cannot zoom in and keeps resizing to node boundries.

### ISSUE THREAD

**Issue by TechMindsYT** [meshtastic/web#159]
Hi,
I am accessing my node using Wifi and a chrome browser via the IP address.

When I select MAP, the map will take a while to move to the location of the discovered nodes, but once there I cannot zoom in and out of the map. Sometimes the node names do not show. If I move off the area where the nodes are and try to zoom, the map auto moves back to the nodes.  Please see the video:

https://youtu.be/VppJNuUmtyg

Anyone else see this issue? Is there a fix?
Thanks,
Matt

**Comment by pdxlocations** [comment]
> Is there a fix? 

Yes!  You'll need to update your node with a full erase and install to update the embedded web client.  A regular firmware update doesn't update the web client. You know you're up to date by checking for the latest commit hash in the bottom left:

<img width="92" alt="Screenshot 2024-02-12 at 5 41 21 PM" src="https://github.com/meshtastic/web/assets/117498748/904644af-6157-4ed0-9912-54cf4843622a">

**Comment by TechMindsYT** [comment]
Thanks, this is fixed with latest firmware.
