### ISSUE TITLE
Enhancing Meshtastic Accessibility: A Call to Support the Heltec V2 firmware through the webflasher.

### ISSUE THREAD

**Issue by HarukiToreda** [meshtastic/web#167]
My thought will always be to be as beginner-friendly as possible. I've noticed that many newcomers, with limited technical knowledge, discover Meshtastic through social media and other channels. In their initial research, some end up purchasing the Heltec V2 by mistake. While it's not the ideal device for Meshtastic, as many like to point out, I believe in supporting those who have shown interest and taken the first step by investing in a board. Telling them they've got the wrong thing or that it's 'not supported' can be discouraging and may dampen the enthusiasm of someone who could become a valuable contributor to our project in the future.

Asking these beginners to navigate the less user-friendly CLI to install firmware can be daunting. To make their journey smoother and more welcoming, I kindly request the addition of the V2 V2.1 to the web flasher. This small gesture can make a significant difference in their initial experience and encourage them to continue exploring the world of Meshtastic, which I've come to love.

I understand that this request might not align perfectly with the current roadmap, but I hope the developers can consider the needs of our non-technical users. Their early experiences can shape the future of our community, and a little flexibility now could lead to a more inclusive and thriving Meshtastic in the future.

![image](https://github.com/meshtastic/web/assets/116696711/6580590f-7aa6-4874-8b06-80e2fee63dac)

**Comment by garthvh** [comment]
It was removed completely, it is not built by the CLI anymore either.

**Comment by rcarteraz** [comment]
> It was removed completely, it is not built by the CLI anymore either.

I think it was just the V1 that was removed from being built.

**Comment by rcarteraz** [comment]
> My thought will always be to be as beginner-friendly as possible. I've noticed that many newcomers, with limited technical knowledge, discover Meshtastic through social media and other channels. In their initial research, some end up purchasing the Heltec V2 by mistake. While it's not the ideal device for Meshtastic, as many like to point out, I believe in supporting those who have shown interest and taken the first step by investing in a board. Telling them they've got the wrong thing or that it's 'not supported' can be discouraging and may dampen the enthusiasm of someone who could become a valuable contributor to our project in the future.
> 
> Asking these beginners to navigate the less user-friendly CLI to install firmware can be daunting. To make their journey smoother and more welcoming, I kindly request the addition of the V2 V2.1 to the web flasher. This small gesture can make a significant difference in their initial experience and encourage them to continue exploring the world of Meshtastic, which I've come to love.
> 
> I understand that this request might not align perfectly with the current roadmap, but I hope the developers can consider the needs of our non-technical users. Their early experiences can shape the future of our community, and a little flexibility now could lead to a more inclusive and thriving Meshtastic in the future.
> 
> ![image](https://private-user-images.githubusercontent.com/116696711/307538624-6580590f-7aa6-4874-8b06-80e2fee63dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3OTY5NTIsIm5iZiI6MTcwODc5NjY1MiwicGF0aCI6Ii8xMTY2OTY3MTEvMzA3NTM4NjI0LTY1ODA1OTBmLTdhYTYtNDg3NC04YjA2LTgwZTJmZWU2M2RhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxNzQ0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmQ5N2UyNjdiNmEwYWQwYjEwNjI2OTU3ZGFkYmU1ZDg1ZGYyZmRmYWVhMzE1MDRjNzQ0ODY0NGNiNjA4NTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P7761GNxNRzoHW9Zr5kRUA02kzYGPmcN_Ecx5mGcOWw)

These devices are hardly sold anymore. 99% of the people using them are the ones that already had them. There might be a couple here and there that accidentally purchase this versus the newer v3 but that’s not reason enough to warrant adding it back to the web flasher imo. 

Also, FYI the appropriate repo for the web flasher is here https://github.com/meshtastic/web-flasher

**Comment by HarukiToreda** [comment]
Those who accidentally purchase the V2 are usually beginners, not experienced enough to know what to look for. Telling a novice to either throw it away and spend more to replace it or learn to use the CLI seems a bit shortsighted and feels like gatekeeping. Plus, a quick search on Amazon shows the V2 still prominently listed. If it's still widely available, shouldn't we consider supporting it to make things easier for newcomers? Unless I'm mistaken about what our goal here is. If so I apologize. @garthvh 

![image](https://github.com/meshtastic/web/assets/116696711/9c3e97fc-e215-494e-b22a-5a11389ee62c)

Sorry about putting this on the wrong place, not sure how to move as I am not an advance user myself.

**Comment by 5mmTech** [comment]
Update 10/27/2025: While I wasn't able to resolve Meshtastic support for the Heltec V2s, I did discover an alternative that uses them, it's called MeshCore. It won't help you get on to the Meshtastic network, but it's an alternative LoRA network. This acutally works out quite nicely for my hobby use as I now will have a presence on both Meshtastic and MeshCore. Hopefully, this discovery helps someone else.

Original Post:

Here I am, 1.5 years after this was opened and I just received a batch of 6 Heltec V2s from a seller on AliExpress. It's my fault for not examining more closely, but it wasn't specified that they were V2. You can only tell by looking at the version on the board in the images and the people complaining in the reviews. I'm not sure if they're working through old inventory, or if they're still being actively manufactured, but they are definitely being sold. And they're not being sold by a fly-by-night. I purchased this set from Tenstar Robot Store, whom I've purchased from numerous times in the past. AliExpress says they have over 100,000 sales on their shop in the last 180 days.

I was able to flash them up to 2.5.22, but that is still too old for the app, so I'll have to see if I have the capabilities to flash them with newer firmware. Anyways, not complaining, just sharing that these are definitely still being sold, and web flasher support would be really cool.
