### ISSUE TITLE
Contextual menu items greyed out and cannot be clicked

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/web#173]
### Description
When accessing the contextual menu in the web client, the menu items are displayed but appear grayed out and cannot be clicked or selected with the mouse cursor. However, typing the text of the desired menu item and hitting enter does execute the corresponding action.

### Steps to Reproduce
1. Open the  web client and connect to your device
2. Open the contextual menu by clicking on it
3. Try to click on the menu items using the mouse cursor

Expected: The clicked menu item should execute the associated action.
Actual: The menu items are grayed out and cannot be clicked, though typing the text and hitting enter works.

### Environment
- Browser: Edge (Also tried Chromium)
- Operating System: macOS 14

### Screen Recording

https://github.com/meshtastic/web/assets/6912600/60f435e5-b262-4bee-a39b-205d8aa3783d

**Comment by NuclearConsent** [comment]
I'm having the same problem.  I created a local environment and rolled back to commit [6113924](https://github.com/meshtastic/web/commit/6113924e462fabf63a2e9f8b841add0aaa4362fe) and that seems to have fixed it. 

A few packages were updated in latest release, but that seems about it. I'll poke around a little later and see what I can find.
