### ISSUE TITLE
Feature Request: Add position_precision Channel Setting to Web Client

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/web#175]
### Description:

Add support for configuring the position_precision setting for channel modules through the web client interface. This setting controls the level of precision for location data sent over a particular channel.

### Details:

The position_precision setting allows users to obfuscate their exact location when sharing position data over certain channels. Higher values reduce precision, providing more privacy by making the shared location less exact.

This setting should be exposed in the web client for each configured channel module that supports location sharing.

### Benefits:
- Allows configuring privacy settings for location sharing per channel
- Gives users control over how precise their shared location data is
- Consistent with other clients

**Comment by Hunter275** [comment]
iOS config:
![IMG_5048](https://github.com/meshtastic/web/assets/3261295/cb148622-08ff-4aae-abd1-3d2f4bee838c)

Steps from left (-) to right (+) for imperial:
1. Within 15 miles
2. Within 7.3 miles
3. Within 3.6 miles
4. Within 1.8 miles
5. Within 0.9 miles
6. Within 0.5 miles
7. Within 0.2 miles
8. Within 600 feet
9. Within 300 feet
10. Within 150 feet

Steps from left (-) to right (+) for metric:
1. Within 23 km
2. Within 12 km
3. Within 5.8 km
4. Within 2.9 km
5. Within 1.5 km
6. Within 700 m
7. Within 350 m
8. Within 200 m
9. Within 90 m
10. Within 50 m

**Comment by Hunter275** [comment]
https://github.com/meshtastic/Meshtastic-Apple/blob/a4e26de6e5423ddeb70d40388d80690006f21bb1/Meshtastic/Views/Settings/Channels.swift

**Comment by Hunter275** [comment]
Default value is `32`

https://github.com/meshtastic/firmware/blob/62b310ac5c868075ef08e4670e2c53a4726cfd43/src/mesh/Channels.cpp#L97

**Comment by rcarteraz** [comment]
Looks like there's an issue with this implementation. Rather than setting the `position_precision` integer between 0-32 as is expected, it's setting it a value that is 1000x the selected approximate distance.

E.g.
12km becomes 12000
5.8km becomes 5800

<img width="666" alt="Screenshot 2024-06-15 at 8 47 29 AM" src="https://github.com/meshtastic/web/assets/6912600/ebe30409-d65a-4c2b-aa04-b32f71953ead">
<img width="712" alt="Screenshot 2024-06-15 at 8 46 36 AM" src="https://github.com/meshtastic/web/assets/6912600/70898f3c-f0ff-44a8-859f-7360d2f3c6cd">

I'll create a new issue for this.
