### ISSUE TITLE
Feature Request: traceroute for webgui

### ISSUE THREAD

**Issue by cracky22** [meshtastic/web#179]
The option to traceroute in the peer list would be great :)

**Comment by cracky22** [comment]
@caveman99 @sachaw @geeksville What do you think about the idea?

**Comment by sachaw** [comment]
I agree, it is certainly a useful feature to have in the web UI. Feel free to have a go at implementing it, I provide guidance if required.

**Comment by cracky22** [comment]
> I agree, it is certainly a useful feature to have in the web UI. Feel free to have a go at implementing it, I provide guidance if required.

Hello Sachaw, I just had to smile a little :) I am a student (16 years old) and am graduating from secondary school this year (I come from Germany, Munich) but I would like to try to incorporate it when I get the chance / time. Do I need certain knowledge? I could offer html/js/css as well as python :)
thank you also for your support

**Comment by sachaw** [comment]
That's great. Prerequisite knowledge isn't strictly require. Just some familiarity with JavaScript should suffice.
It's work looking through the codebase to wrap your head around what's going on. If you make any changes, feel free to open a PR and I can give feedback/assistance as required

**Comment by fifieldt** [comment]
Hi @sachaw , @cracky22 -- I've hacked together the start of some basic functionality over here: 

https://github.com/meshtastic/web/pull/211 

I probably won't be able to progress that much more before I go on holiday, so if anyone wants to take it over and hack on it over the next couple weeks please do feel free!

**Comment by fifieldt** [comment]
I've been using the code in #211 for the past couple weeks and asked some people in the local community to test as well. Result is: it works reliably :)

I don't have the skill to design a great UI integration, so hoping someone might be able to help get this over the line.
