### ISSUE TITLE
RAK4631 hangs on "Reading device configuration"

### ISSUE THREAD

**Issue by max-mapper** [meshtastic/web#18]
I have a RAK4631 running firmware-rak4631_5005-1.2.55.9db7c62.uf2. I am running meshtastic-web locally and running chromium on linux with Web Bluetooth enabled. I am able to see my device when I hit Connect and it pops up the BLE device selector, but when I select it it just hangs here: 

![image](https://user-images.githubusercontent.com/39759/156711753-a1bbc9d3-8a18-452f-b970-892224e19fc5.png)

On my device serial console I see:

```
??:??:?? 89 BLE Connected to <laptop>
??:??:?? 89 CCCD Updated: 1
??:??:?? 89 fromNum 'Notify' enabled
??:??:?? 90 toRadioWriteCb data 0x20011ada, len 7
??:??:?? 90 Client wants config, nonce=548990099
??:??:?? 90 Starting API client config
```

Thank you

**Comment by sachaw** [comment]
This should now be fixed.
