### ISSUE TITLE
Implement add channels querystring value in the QR code generator

### ISSUE THREAD

**Issue by garthvh** [meshtastic/web#180]
Add a toggle to replace / add channels in the QR code generator.  replace will have no query string value or add=false, adding channels will append add=true to the query string.

**Comment by KirilCycle** [comment]
@garthvh Hello! Can I try to implement this, please?

**Comment by Hunter275** [comment]
Current iOS implementation:

Replace
![IMG_5043](https://github.com/meshtastic/web/assets/3261295/5417e3d2-feba-4223-bb75-0c441b2c99fa)

Add
![IMG_5042](https://github.com/meshtastic/web/assets/3261295/c46c90c6-41f3-4026-a1fe-2e6e903cc736)
