### ISSUE TITLE
Connection from Web always uses "meshtastic.local", remote connection ignored

### ISSUE THREAD

**Issue by michaelkleinhenz** [meshtastic/web#19]
On v1.2.52.b63802c, it is not possible to connect the web UI to the API if `meshtastic.local` does not resolve. In this case, the routing setup does not support `.local` resolving. 

Selecting "Remote" and entering the device IP also does not work and is aparrently ignored.

![Screenshot](https://user-images.githubusercontent.com/7101098/156999427-e6c0909c-d3b6-4f44-818f-2a08bd4b6712.png)

**Comment by sachaw** [comment]
Fixed in [1202345](https://github.com/meshtastic/meshtastic-web/commit/1202345d69f5b12d33ccb3dab501ead5251b508c)
