### ISSUE TITLE
Channel keys need to tell what format they're expected to be entered in

### ISSUE THREAD

**Issue by KyleMaas** [meshtastic/web#196]
I just posted something similar over in https://github.com/meshtastic/firmware/issues/3855 but it is applicable here as well.

There's nothing in the interface that tells you what format keys are expected to be in - hex, Base64, or even just freeform-and-hashed.  As such, it took me some trial and error to generate and set a key, because my initial assumption based on the docs referring to the 0x01 primary channel was that it was expecting a string of hex digits, but it would just silently fail if I did that.  There should be some kind of hint in the UI that tells that it's expecting a Base64-encoded string.

**Comment by Hunter275** [comment]
Closed now that there is a password generator
