### ISSUE TITLE
[Feature Request]: show which nodes are heard via radio and which via mqtt in the web interface

### ISSUE THREAD

**Issue by sq5bpf** [meshtastic/web#209]
### Platform

Linux Native

### Description

In the web interface when running on portduino, when "nodes" is selected, please show which node is avaliable only via mqtt, and which via radio (including hop count). 

This feature request might be a general one, but i only have the linux native platform, so can't compare.

**Comment by fifieldt** [comment]
#195 and #209 are the same request.
