### ISSUE TITLE
 HopLimit could be set >7

### ISSUE THREAD

**Issue by karamo** [meshtastic/web#217]
In the Web-Client HopLimit could be set >7

**Comment by rcarteraz** [comment]
> In the Web-Client HopLimit could be set >7

The firmware will automatically set it to 3 (default) if you try anything higher than 7.

**Comment by karamo** [comment]
yes, but it would be shown wrong in the web-client.

```
   if (p->hop_limit > HOP_MAX) {
        LOG_WARN("hop limit %d is too high, setting to %d\n", p->hop_limit, HOP_RELIABLE);
        p->hop_limit = HOP_RELIABLE;
    }
```
