### ISSUE TITLE
[Bug]: unable to set fixed position in web interface

### ISSUE THREAD

**Issue by Obliterous** [meshtastic/web#245]
### Hardware

Heltec V3

### Connection Type

Serial

### Local or Hosted

https://client.meshtastic.org

### Firmware Version

2.3.10.d19607b

### Description

when using web UI  and selecting fixed position with no GPS, there is nowhere to enter for Lat/long.
![image](https://github.com/meshtastic/web/assets/195223/d69349a4-e329-45df-8808-e035b95888f4)

**Comment by rcarteraz** [comment]
> ### Hardware
> Heltec V3
> 
> ### Connection Type
> Serial
> 
> ### Local or Hosted
> https://client.meshtastic.org
> 
> ### Firmware Version
> 2.3.10.d19607b
> 
> ### Description
> when using web UI and selecting fixed position with no GPS, there is nowhere to enter for Lat/long. ![image](https://private-user-images.githubusercontent.com/195223/340935563-d69349a4-e329-45df-8808-e035b95888f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NzY2NDYsIm5iZiI6MTcxODc3NjM0NiwicGF0aCI6Ii8xOTUyMjMvMzQwOTM1NTYzLWQ2OTM0OWE0LWUzMjktNDVkZi04ODA4LWUwMzViOTU4ODhmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwNTUyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGIwOTYzMGM0MDBlYmViOTBiM2VjOWQ5MzczZmRmYTQ3YjdhNjI5MjMwNzEyYTNhMmViMjA4MmU5YjUwNzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xwNmMttUhh2yOq1Ibg0hyEWykGILkCYv40p-12OJytE)
> 
> ### Relevant console output
> _No response_

Duplicate of https://github.com/meshtastic/web/issues/87

**Comment by Hunter275** [comment]
Closing due to duplicate, fix is being worked on
