### ISSUE TITLE
Settings menu does not reflect device settings, changes = lockup

### ISSUE THREAD

**Issue by charminULTRA** [meshtastic/web#25]
When connected via Serial, the settings configured on the Meshtastic device (RAK 4631 in this case), are not accurately reflected in the web interface settings menu. For instance, I have set my radio to LongFast, US region, but the Lora settings on the Web interface says "VLongSlow" and "Unset".

Further, changing the setting and hitting Save results in the interface being blurred out, with "Loading" displayed indefinitely.

**Comment by charminULTRA** [comment]
I can confirm this also happens on T-Echo, changing settings freezes both the Web interface and the device itself. Web interface just stays stuck on "Loading".

**Comment by charminULTRA** [comment]
The changes also do not take effect.

**Comment by sachaw** [comment]
This should now be working.
