### ISSUE TITLE
[Bug]: Channel > Downlink Enabled does not work

### ISSUE THREAD

**Issue by karamo** [meshtastic/web#256]
### Hardware

Not Applicable

### Connection Type

Serial

### Local or Hosted

https://client.meshtastic.org

### Firmware Version

2.3.14

### Description

Channel > Downlink Enable does not work.
Web 2566395

**Comment by Hunter275** [comment]
I cannot replicate this. I am able to disable/enable Downlink settings and I confirmed they match when paired to an iOS device as well.

**Comment by karamo** [comment]
Yes, in Web-Client you can enable/disable. > Submit
You are right, ok, now it ist working. I don't know what it was.

**Comment by Hunter275** [comment]
@karamo sometimes if you're fast enough you can get to the setting before it loads the config from the device and any of those changes won't save. That's a bug in itself for the entire app though.
