### ISSUE TITLE
[Bug]: Sort Nodes by Last Heard do nothing

### ISSUE THREAD

**Issue by karamo** [meshtastic/web#257]
### Hardware

Not Applicable

### Connection Type

Serial

### Local or Hosted

https://client.meshtastic.org

### Firmware Version

2.3.14

### Description

Sort Nodes by **Last Heard** do nothing.
Web 2566395

**Comment by Hunter275** [comment]
Bug is confirmed, this used to work but now it doesn't. Digging in now.

**Comment by Hunter275** [comment]
@karamo try this build: https://web-qvjube80s-meshtastic.vercel.app/

**Comment by karamo** [comment]
> @karamo try this build: https://web-qvjube80s-meshtastic.vercel.app/

Thank you, it is working ok.
