### ISSUE TITLE
[Bug]: Update Channel Password flavor text

### ISSUE THREAD

**Issue by Hunter275** [meshtastic/web#261]
### Hardware

Not Applicable

### Connection Type

HTTP, Bluetooth, Serial

### Local or Hosted

http://meshtastic.local, https://client.meshtastic.org

### Firmware Version

Any

### Description

This flavor text needs updated to show the different PSK sizes:

![image](https://github.com/meshtastic/web/assets/3261295/dcbf2b2d-ab7e-4d84-b57e-27176667420f)

**Comment by Hunter275** [comment]
I believe you're only able to enter in the correct number of characters per PSK encryption type on iOS, maybe mirror that functionality here as well

**Comment by garthvh** [comment]
Both android and iOS use the same validation now base 64 for the actual key

**Comment by KyleMaas** [comment]
See also: #196
