### ISSUE TITLE
[Q]: 1 hop, 2 hops?

### ISSUE THREAD

**Issue by cracky22** [meshtastic/web#267]
### Hardware

Heltec V3

### Connection Type

Bluetooth

### Local or Hosted

https://client.meshtastic.org

### Firmware Version

v2.4.1.394e0e1

### Description

![image](https://github.com/user-attachments/assets/6b252d38-4eb8-41a2-9183-abb3bad4d757)
1 hop, 2 hops?

**Comment by Hunter275** [comment]
This one made me laugh out loud
