### ISSUE TITLE
Cannot access the node web interface if GitHub API rate limit exceeded

### ISSUE THREAD

**Issue by fabfurnari** [meshtastic/web#27]
If I try to access the node web interface (eg. connected to the local wifi network) this error appears: 

![Screenshot_2022-07-28_00-58-06](https://user-images.githubusercontent.com/554134/181386587-7065ad4b-d59d-4f63-99b4-b04eed4c21a0.png)

In the browser console can see that this could be correlated with GH API limit:
![Screenshot_2022-07-28_00-59-40](https://user-images.githubusercontent.com/554134/181386737-eb87c846-d4ba-4cf2-b526-09adf0c8d094.png)

This could be also confirmed by resetting the API rate limit (eg. changing own IP address) and refreshing: the web interface shows up nicely.

IMHO a local web interface should be not dependent on external services to show.

Thanks for all your work on Meshtastic!

**Comment by mc-hamster** [comment]
moved to web

**Comment by garthvh** [comment]
What firmware version are you running?

**Comment by garthvh** [comment]
> IMHO a local web interface should be not dependent on external services to show.

I get this assumption, but it does not really match the state of mobile phone browser support or the amount of space available on the local web server.

The web ui is really used more as a base station / bridge where there is internet than as an offline mobile messaging client.  Cutting down on external dependancies is a goal, but there is a very limited amount of space. My guess is that these GitHub calls for releases are for doing firmware updates, there is no way to store all of these locally.

**Comment by fabfurnari** [comment]
Hi, I'm using the `1.2.65.0adc5ce` with a LilyGo LORA V2.1 1.6.1

I understand the limited space on the device itself, maybe the error could be changed to a non-critical one?

**Comment by sachaw** [comment]
@fabfurnari If you upgrade to 1.3 you should no longer have this issue, if that's not the case, please reopen this issue.
