### ISSUE TITLE
[Bug]: Unable to enable Canned Messages Module or set list of messages

### ISSUE THREAD

**Issue by adamwearsblack** [meshtastic/web#270]
### Hardware

Heltec V3

### Connection Type

Bluetooth

### Local or Hosted

https://client.meshtastic.org

### Firmware Version

2.4.0

### Description

When using the web client to set up Canned Messages on Heltec V3 running Meshtastic 2.4.0, I was able to enable to module and set all the GPIO pins. However when the node rebooted it said "Canned Messages Module disabled". I tried disabling the module and re-enabling via the web client but the module remained disabled. Additionally there was no place to set the list of messages. 

I re-attempted the configuration using the Apple app and was able to successfully enable the canned messages module and also set the list of messages. Since making this change, the canned messages work as expected. 

I believe this bug may be an issue with the web client.

**Comment by rcarteraz** [comment]
> ### Hardware
> Heltec V3
> 
> ### Connection Type
> Bluetooth
> 
> ### Local or Hosted
> https://client.meshtastic.org
> 
> ### Firmware Version
> 2.4.0
> 
> ### Description
> When using the web client to set up Canned Messages on Heltec V3 running Meshtastic 2.4.0, I was able to enable to module and set all the GPIO pins. However when the node rebooted it said "Canned Messages Module disabled". I tried disabling the module and re-enabling via the web client but the module remained disabled. Additionally there was no place to set the list of messages.
> 
> I re-attempted the configuration using the Apple app and was able to successfully enable the canned messages module and also set the list of messages. Since making this change, the canned messages work as expected.
> 
> I believe this bug may be an issue with the web client.
> 
> ### Relevant console output
> _No response_

The web client lacks the ability to set the messages due to how they're set. This is actually a duplicate of an already open issue: https://github.com/meshtastic/web/issues/123
