### ISSUE TITLE
[Feature Request]: Add Footer Sitewide

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/web#273]
### Description

I created a footer component to add the required Vercel footer per our sponsorship agreement but cannot get it to be visible across the site without scrolling. 

```tsx
import React from "react";

const Footer = () => {
  return (
    <footer
      className="flex justify-center p-4"
      style={{
        backgroundColor: "var(--backgroundPrimary)",
        color: "var(--textPrimary)",
      }}
    >
      <p>
        <a
          href="https://vercel.com/?utm_source=meshtastic&utm_campaign=oss"
          className="hover:underline"
          style={{ color: "var(--link)" }}
        >
          Powered by ▲ Vercel
        </a>{" "}
        | Meshtastic® is a registered trademark of Meshtastic LLC. |
        <a
          href="/docs/legal"
          className="hover:underline"
          style={{ color: "var(--link)" }}
        >
          {" "}
          Legal Information
        </a>
        .
      </p>
    </footer>
  );
};

export default Footer;
```

**Comment by KomelT** [comment]
I know PR 274 was tmp, but it would look better if the footer were always on the bottom.
![image](https://github.com/user-attachments/assets/02e4651d-18b0-479f-8afe-121bdd858e49)

**Comment by Hunter275** [comment]
@KomelT Agreed with the page you posted but what about the settings pages? Those currently only show past the viewport

**Comment by Hunter275** [comment]
@rcarteraz thoughts?

**Comment by rcarteraz** [comment]
> I know PR 274 was tmp, but it would look better if the footer were always on the bottom. 

I think it was changed so it wasn't really temporary anymore, wasn't it @Hunter275? The new one should appear at the bottom of all pages. At least it did in my testing.

**Comment by rcarteraz** [comment]
@Hunter275 I think the only thing that could be better is if pages like Config acted the way the Nodes page does. The footer is always viewable at the bottom without scrolling, and the scrolling happens inside the nodes view. Video below for visualizing.

https://github.com/user-attachments/assets/90f69e6f-0ff9-489a-adab-5b5d8934fa27

**Comment by Hunter275** [comment]
@rcarteraz They do appear at the bottom, what we're talking about is it should "stick" to the bottom of all the pages (like it does in Map and Messages).

In Settings and the Dashboard it does not stick to the bottom.

**Comment by rcarteraz** [comment]
> @rcarteraz They do appear at the bottom, what we're talking about is it should "stick" to the bottom of all the pages (like it does in Map and Messages).
> 
> In Settings and the Dashboard it does not stick to the bottom.

Oops. My bad... Yes, I think it would be better visually if it sticks. The Nodes pages is a good example of how it should work.

**Comment by KomelT** [comment]
> @KomelT Agreed with the page you posted but what about the settings pages? Those currently only show past the viewport

That is ok. If there is content for more than one page let it be at the end (out of viewport).
If there is less content then the footer should be at the bottom.

**Comment by Hunter275** [comment]
https://web-ilbhp9z3q-meshtastic.vercel.app/
