### ISSUE TITLE
WiFi PSK validation does not allow for long keys

### ISSUE THREAD

**Issue by Noki** [meshtastic/web#28]
A Wifi PSK can be 8 to 63 chars in ASCII / 64 chars in HEX. Long keys do not work:

![image](https://user-images.githubusercontent.com/198902/182838004-f954d52e-4f8f-4bd0-bcaa-7383243028c1.png)

The PSK validation should be adjusted.

**Comment by caveman99** [comment]
Indeed the Protobufs have the right length

*WiFiConfig.ssid max_size:33
*WiFiConfig.psk max_size:64

**Comment by garthvh** [comment]
The practical limit is in characters is going to be something less than the byte limit.  Probably about 60 characters for PSK, the text on the error is wrong, but the text on labels and validation are not finished, when I tested this allowed an expected password max length of about 60 characters.

**Comment by garthvh** [comment]
63 characters saved which is the expected limit

**Comment by Noki** [comment]
@garthvh can you please reference a commit that fixes the 16 char limit in the web client? Or why did you close this one?

**Comment by garthvh** [comment]
We saved a 63 character value yesterday, but you are correct it was from the CLI, not the Web UI

**Comment by sachaw** [comment]
Fixed in https://github.com/meshtastic/meshtastic-web/commit/258ffc2ec64640ff967e1b274ba6a79fc83f2076
