### ISSUE TITLE
Web page never connects to either Serial or http

### ISSUE THREAD

**Issue by scarolan** [meshtastic/web#30]
I have managed to install the web panel on one of my devices, but am unable to load info in the UI.  It just spins.  I get the same thing with your hosted version.

![image](https://user-images.githubusercontent.com/403332/184450792-0be3b67c-b6e5-4e94-bbc7-c15fd834477b.png)

**Comment by scarolan** [comment]
And this is what I see after connecting to Serial:

![image](https://user-images.githubusercontent.com/403332/184450993-80e1591d-0d19-47f2-bfee-786e86b10258.png)

It also just spins like the example above.

**Comment by sachaw** [comment]
Thanks for filing the issue, firstly the TBA-TBA you see under serial will be fixed soon, as for why it's not working is another story.

For http connections, there should be no issues whatsoever, could you please open your devtools F12 then try connecting again and tell me what the error is?

**Comment by garthvh** [comment]
Based on an earlier issue I think he updated the webui from a 1.2.65 device is that correct @scarolan

**Comment by sachaw** [comment]
@scarolan can you please confirm your firmware version?

**Comment by sgofferj** [comment]
Same issue here with serial. Webserial generally works for me. I regularly use it with ESPHome. But the Meshtastic UI fails to connect.

**Comment by sgofferj** [comment]
@sachaw 
http does work locally but not from client.meshtastic.org. That seems to be a mixed content issue. The web UI tries to contact http://meshtastic.local/hotspot-detect.html but client.meshtastic.org is served via https.

**Comment by sgofferj** [comment]
@sachaw 
for serial I get a bunch of errors on the console:
```
[INFO] iSerialConnection.readFromRadio
Device errored or disconnected: NetworkError: The device has been lost.

[ERROR] iHttpConnection.pingFailed to execute 'fetch' on 'Window': The user aborted a request.
j_ @ index.a124fda7.js:97
log @ index.a124fda7.js:99
(anonymous) @ index.a124fda7.js:99
Promise.catch (async)
ping @ index.a124fda7.js:99
connect @ index.a124fda7.js:99
(anonymous) @ index.a124fda7.js:99
setTimeout (async)
connect @ index.a124fda7.js:99
await in connect (async)
(anonymous) @ index.a124fda7.js:99
```

**Comment by rohanki** [comment]
> @sachaw http does work locally but not from client.meshtastic.org. That seems to be a mixed content issue. The web UI tries to contact http://meshtastic.local/hotspot-detect.html but client.meshtastic.org is served via https.

Same issue here. I have also tried using the IP address instead of meshtastic.local, and client.meshtastic.org will try and connect to my IP using http not https.

**Comment by sachaw** [comment]
Can everyone please confirm they are running the latest 1.3.x firmware?

**Comment by sgofferj** [comment]
1.3.38.
Mixed content errors have not much to do with the firmware though. That's an issue with the web client.

**Comment by Noki** [comment]
As a workaround insecure content can be enabled for just a single site in chrome:

You can click the secure icon and go to "Site Settings". You can then allow "Insecure content". Afterwards you can access a meshtastic device in the network.

![image](https://user-images.githubusercontent.com/198902/186474252-42e2234d-63f6-48b3-81d5-a012fd1a5f82.png)

![image](https://user-images.githubusercontent.com/198902/186474269-f9274e3a-6f5e-4fcc-84b5-8b8dc35517b8.png)

**Comment by sachaw** [comment]
This should now be fixed as I force tls connections if the page is served over https

**Comment by scarolan** [comment]
Rad thanks for the fix.
