### ISSUE TITLE
[Bug]: Bluetooth not being enabled

### ISSUE THREAD

**Issue by andy1v** [meshtastic/web#328]
### Category

BLE

### Hardware

T-Deck

### Firmware Version

2.5.3

### Description

In web client can not Enable Bluetooth
After you enter in settings  bluetooth and enable, press button save device will restart in next 20 sec and bluetooth is still disable

**Comment by caveman99** [comment]
If Wifi is enabled bluetooth will stay disabled. They can not be on at the same time. Limitation of the Hardware.

**Comment by andy1v** [comment]
I will double check,but just like I remember wifi was off
Thank you

**Comment by andy1v** [comment]
Team,
I double check and wifi is off and still [is the same issue 
When enable bluetooth and save config device is going to reboot an is not activating bluetooth 

Thank you

**Comment by Hunter275** [comment]
Bug confirmed

**Comment by Hunter275** [comment]
@andy1v 

I cannot replicate this issue, please confirm that WiFi is DISABLED like in the screenshot:
<img width="280" alt="image" src="https://github.com/user-attachments/assets/a0d82220-87ff-43a9-a882-b5d46245943b">

Save the settings and let the device reboot THEN enable Bluetooth and save the settings.

**Comment by tomhanax** [comment]
Same problem here on 2.5.21. Connecting via serial using client.meshtastic.org. Wifi off, ble off. When I enable ble an save, device restarts but still no ble and gui switcher is off.
