### ISSUE TITLE
[Bug]: SenseCAP Card Tracker T1000-E for Meshtastic shows 101% of Akku.

### ISSUE THREAD

**Issue by Dtrieb** [meshtastic/web#335]
### Hardware

Other

### Connection Type

Serial

### Local or Hosted

https://client.meshtastic.org

### Firmware Version

2.5.9.936260f

### Description

Connect with a SenseCAP Card Tracker T1000-E for Meshtastic shows 101% of Akku.
See Screenshot.

![chrome_2024-11-08_16-38-36](https://github.com/user-attachments/assets/e8612152-8f12-4102-9b54-827a4cd00d67)

### Relevant console output

```Shell
battery_level=101, voltage=4.204000,
```

**Comment by KomelT** [comment]
Hi, for connected nodes on power supply is normal it shows 101%. I assume it is a feature so you know that it is charging.

**Comment by thebentern** [comment]
This is a display bug on the web client that needs to be fixed. 101% means charging.
