### ISSUE TITLE
Cannot type letter "k" in app text fields

### ISSUE THREAD

**Issue by ajmcquilkin** [meshtastic/web#42]
![image](https://user-images.githubusercontent.com/46639306/195436778-467a74f1-7427-4646-abc1-6bbe1d1e3601.png)

Due to this code in `src/components/CommandPalette/Index.tsx`, the user is not able to type the letter `"k"` into any text input fields within the application.

**Repro:** Attempt to type the name `"Kite"` into the name of a connected mesh node.

**Comment by sachaw** [comment]
Thanks for noticing & the fix!

**Comment by ajmcquilkin** [comment]
Yeah sure! I thought I had forgotten how to spell for a second haha
