### ISSUE TITLE
Web client doesn't like the "k" key.

### ISSUE THREAD

**Issue by goatzillax** [meshtastic/web#45]
Chrome on Ubuntu and Chromebook.

Client seems to literally not recognize my "k" key.

**Comment by sachaw** [comment]
Can you please see if your issue has been resolved by using the webui available at https://client.meshtastic.org

If that is the case, the fix will be included in the next firmware release.

**Comment by goatzillax** [comment]
Unfortunately I can't connect with that client.  It doesn't seem to allow me to de-select TLS.  I don't think I have TLS on my device.

Your device will generate a TLS certificate, also you are able to connect to them using Bluetooth and serial

**Comment by goatzillax** [comment]
FWIW I upgraded to 1.3.45 and the client appears to recognize my 'k' key now.  Checked against all \w in fact.
