### ISSUE TITLE
Dark mode doesn't work

### ISSUE THREAD

**Issue by IZ1IVA** [meshtastic/web#49]
Ctrl-K -> Application -> Toggle Dark Mode, nothing happens.

Tried on Brave and Firefox with local client, as I can't find the device from client.meshtastic.org

Cheers

**Comment by ajmcquilkin** [comment]
Just looked into this, looks like dark mode isn't supported in the client yet (or at least I can't find the code for it). I'll push a change marking that and other similar commands as work-in-progress (WIP).
