### ISSUE TITLE
BUG: Position always center Melbourne in the Web View

### ISSUE THREAD

**Issue by Dtrieb** [meshtastic/web#56]
The Android App shows me my Position, but the Web means:

**Current Location
No Fix.**

![chrome_2022-10-31_15-39-08](https://user-images.githubusercontent.com/3650284/199034884-57579b37-86a3-4c97-b55f-84a32ed811aa.png)

**Comment by Dtrieb** [comment]
Also didn't show my position in the map on the web.

**Comment by sachaw** [comment]
Does your device have it's position listed on it's screen?

**Comment by Dtrieb** [comment]
Now it works (2.0.7) but the location from the map jumps to Melbourne. If I switch between the entries it always get back to Melbourne.

![chrome_2022-12-14_14-58-05](https://user-images.githubusercontent.com/3650284/207614390-88a3fcd3-ba16-44d8-ad3b-3622e99a08ab.gif)

**Comment by GMart** [comment]
Similar issue for me. The map always starts at Melbourne. I am using a fixed location. I have tried clearing cookies, and no luck. Also, for me the Current Location sidebar says something like "Current Location

16T EL 96628 67738"
Which doesn't seem to be a Lat/long location. I think the formatting is bugged? 
The node I am connected to is running 
2.0.7.91ff7b9-d/20

The other devices on the mesh can see the location.

**Comment by sachaw** [comment]
Currently the map doesn't auto center on your nodes (will do soon)
As for formatting, it's MGRS.
I'll make an option so you can pick the coordinate format of your choosing

**Comment by sachaw** [comment]
This has now been implemented, When the map loads, it will do one of three things:
1. No nodes with position: Map center will be Melbourne as before
2. 1 node with a position: Map will center on that node with a zoom level of 12
2. multiple nodes: Map will create an automatic bounding box to fit all nodes within.

**Comment by Dtrieb** [comment]
Reopen, because new Version have the same problem.

**Comment by sachaw** [comment]
Does any of your devices have a position? It should auto center on them.

**Comment by Dtrieb** [comment]
> Does any of your devices have a position? It should auto center on them.

Yes, the device has a fixed position. (I also see it on the map.)


![chrome_2023-02-13_20-23-15](https://user-images.githubusercontent.com/3650284/218554155-4bae2e82-0cef-4b6f-b530-56726d3eb65a.gif)
