### ISSUE TITLE
Enhancement: Batch save for multiple setting changes or unloadable config

### ISSUE THREAD

**Issue by xman5735** [meshtastic/web#58]
When setting up multiple meshtastic devices, taking the time for the device to reboot after every setting change takes extra time and seems redundant. It would be nice to make all my changes and then click save or to click save on each page and then reboot at the end.

Alternatively, being able to upload a preconfigured config file with the changes would work, but is less ideal in my opinion.

**Comment by garthvh** [comment]
Each group of settings (config or module) causes a reboot in the firmware after they save. This is to enable the use of the admin channel for management. The previous config got too large to send in a mesh packet.

**Comment by xman5735** [comment]
I see. It would be nice to commit the changes at the end of getting settings ready.  Then the webserver would run through the stack of changes one by one, including reboots, until all changes are applied. I understand that this would be a low priority QOL change. 
I appreciate the fast response.

**Comment by sachaw** [comment]
This is now in progress, The UI is provisioned, just need to get it to work right.

**Comment by sachaw** [comment]
Should work now
