### ISSUE TITLE
Bug: Bluetooth setting is inaccurate and unchangable

### ISSUE THREAD

**Issue by xman5735** [meshtastic/web#59]
When modifying the bluetooth config, enable slider is off when bluetooth is confirmed on with (5) TTGO Tbeam v1.1(s). Changing that setting, or any other setting on the config, will not make any changes. Either the save button is unclickable or the reboot will revert to original state. 
![Screenshot 2022-11-08 104433](https://user-images.githubusercontent.com/23144022/200610812-755f6f61-571d-41e8-ac50-ebf79915ca9d.png)

**Comment by sachaw** [comment]
Fixed in https://github.com/meshtastic/web/commit/5156a67fc4ee4679a279666e3b9c9be748a94a28
