### ISSUE TITLE
[UX] Easier/faster connection when accessing the node's web interface via IP instead of a hostname

### ISSUE THREAD

**Issue by renekliment** [meshtastic/web#62]
Hi! :cat2:
There are cases when the user needs to access the web interface running on the node by IP (`http(s)://IP`), because the node itself cannot be reached at `http(s)://meshtastic.local`. 

In these cases the user needs to type the node's IP in the input where there is the pre-filled address. Copying the address from the browser's URL input doesn't make it easier, because when selecting the IP, _modern_ browsers put the whole URL in the clipboard - `http(s)://IP/` and the users needs to remove various things from the input after pasting. This all leads to bad UX.

Suggestions for a solution:
- The pre-filled URL could be the current browser origin instead of the default `http://meshtastic.local` when the website is served from a node.
- There could be a button like `Connect to this node` (not sure about the label) that would try to connect to the node with the same origin address as the web page when the website is served from a node.

**Comment by sachaw** [comment]
I've changed the behavior to this:
```ts
ip: ["client.meshtastic.org", "localhost"].includes(
        window.location.hostname
      )
        ? "meshtastic.local"
        : window.location.hostname,
```

Please let me know if you have any other improvements
