### ISSUE TITLE
Can't set user information

### ISSUE THREAD

**Issue by Jasons81** [meshtastic/web#64]
When trying to set the user information it acts as if the ID field is blank even when populated.

![image](https://user-images.githubusercontent.com/121370494/210078064-865de4c5-e309-4ba8-96e2-ab74ce6d41ce.png)

**Comment by sachaw** [comment]
Should be fixed in https://github.com/meshtastic/web/commit/f7fe27d621921010fb186107a31940bdf0344c0d
