### ISSUE TITLE
Web Interface reset before i can send a message through the text field

### ISSUE THREAD

**Issue by homesec24** [meshtastic/web#67]
If i chat over the WEB Interface and the node has a connection to the main mqtt server and i want to write, the text field always do a reset and the text is gone ... as a workaround i write my text to the url field from the browser and do a copy/paste and press send immediately.

**Comment by sachaw** [comment]
Fixed in https://github.com/meshtastic/web/commit/0b2140ed2fafa8c0e9384074c2372256adac06de
