### ISSUE TITLE
[Bug] Unable to save changes to owner name/short name

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/web#68]
@sachaw I think #66  may have introduced another bug. When attempting to save the owner name or short name it now pops up with "No Response Received" and does not save the change. 
<img width="287" alt="Screenshot 2023-01-07 at 10 54 36 AM" src="https://user-images.githubusercontent.com/6912600/211164219-b678cc31-6f8e-426e-9a86-1be501261982.png">

**Comment by sachaw** [comment]
Definetly not related to #66, I'll look into it, not sure why it's not saving, but the error is because no ack was received.
What fw version are you runnuing?

**Comment by rcarteraz** [comment]
> Definetly not related to #66, I'll look into it, not sure why it's not saving, but the error is because no ack was received.
> What fw version are you runnuing?

Ah. Okay, wasn’t sure as it’s a new issue right after that fix and was also the names but I see what you’re saying. Someone reported the issue in the discord with 2.0.12 and I was able to recreate it with 2.0.8, 2.0.11 and 2.0.12.

**Comment by sachaw** [comment]
Fixed in https://github.com/meshtastic/web/commit/0f6b0416df912a7344ac85dbc36b7f9eb4559552
