### ISSUE TITLE
[Bug]: Unable to Save

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/web#73]
Adding this for tracking purposes to due to repeated questions about it. @sachaw I'm aware you are working on this and have partially fixed it based on your message in the discord. 

>Got a WIP fix as a part of the config overhaul, currently only the device config, excluding 'User' will save, but it should allow you to make any edits you wish then apply them all at once.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/web-ui-not-saving-secondary-channels/7191/3
