### ISSUE TITLE
Purpose of config number bubbles unclear

### ISSUE THREAD

**Issue by ajmcquilkin** [meshtastic/web#75]
The purpose of the new config bubbles within the `DeviceConfig` component is not immediately clear to the user. This might warrant a tooltip, or some other UI element to tell the user how to interpret this number.

![Screenshot_20230129_125434](https://user-images.githubusercontent.com/46639306/215345877-01400c98-6552-4756-944c-7099bea0e5d3.png)

**Comment by sachaw** [comment]
This is now changed, those were placeholder.
Eventually there will be an indicator of how many unsaved changes there are
