### ISSUE TITLE
Map display UI crashes to white screen 

### ISSUE THREAD

**Issue by devnulling** [meshtastic/web#76]
Firmware: V2.0.14.2baaad8 beta
Hardware: T-beam
Connection: Serial
Browser: Chrome

After the devices get a GPS lock, clicking on the Map display in the web app, the UI will crash to a white screen. Seeing these errors in the console:

```index-d2520ad6.js:40 Error: coordinates must be an array of two or more positions```

```Uncaught Error: coordinates must be an array of two or more positions```

**Comment by sachaw** [comment]
Can you please confirm is this is still an issue
