### ISSUE TITLE
[bug] tlora-v2-1-1.6-2.0.16.2242b68 the nodes geo map does'nt show the node name clicking on icons

### ISSUE THREAD

**Issue by vinloren** [meshtastic/web#78]
Using https://client.meshtastic.org/ vith serial usb connection and hedge or chrome browser I can show the geomap relevant to the peers node in mesh but I can't get any node name by clicking on relevant node icon shown there.

**Comment by sachaw** [comment]
fixed

**Comment by vinloren** [comment]
Well done, thanks a lot Sachaw.
