### ISSUE TITLE
[bug] tlora-v2-1-1.6-2.0.16.2242b68 sending messages does'nt work at all

### ISSUE THREAD

**Issue by vinloren** [meshtastic/web#79]
Using https://client.meshtastic.org/ with hedge or chrome browser and serial usb connection to the Tlora device, any text set in the dedicated input text field is not succesfully sent to the mesh as a ! appears shortly after in the little circle beneath the icon of my device shown in the message screen. Actually nobody in the mesh could receive the message. 
Feb. 7th: after further investigation I can state that actually the messages go thru the HTTP / mqtt path of my router_client and reach the part of the mesh addressed by the gateway, the part of the mesh linked via radio to my Tlora router_client is not addressed probably because the router_client chooses the http path only disregarding the tx radio. If I send messages via App IP connected to the router_client the messages to 0 Channel work nicely and both the http path and the tx radio path are activated and the whole mesh is reached.

**Comment by micheljung** [comment]
Same here with ESP32; regardless of whether I use https://client.meshtastic.org/ or connect to the device via HTTP, messages do not get sent. In Chrome's Network monitor, I see no request.

Sending from the Android App works just fine.

**Comment by uzsito** [comment]
I'm afraid the same happens with my
Tbeam 2.0.16
T-echo 2.0.16 also.
☹️
tried serial & http, outgoing messages do not work. incoming is ok.

**Comment by ajmcquilkin** [comment]
This is likely an issue where the web client is requesting a response from the remote nodes, but the nodes don't have any data to respond with. This causes a routing error and causes the remote nodes to ignore the message, which is why the error marker is shown. There is a PR up on the JS repo to fix this issue ([link](https://github.com/meshtastic/js/pull/64))

**Comment by sachaw** [comment]
Should be fixed

**Comment by vinloren** [comment]
Ok thanks, it works nicely now!
