### ISSUE TITLE
Changing the device name immediately reboots

### ISSUE THREAD

**Issue by micheljung** [meshtastic/web#80]
Using https://client.meshtastic.org/ and connecting to an ESP32 via serial, while entering the "Device Name" the device suddenly reboots  even though "Save & Reboot" wasn't pressed.

**Comment by ajmcquilkin** [comment]
This issue doesn't appear to be limited to just the device name field, I'm getting this happening on the short name too. I'll see if I can find any more info

**Comment by ajmcquilkin** [comment]
Update on previous comment -- it looks like the client doesn't handle the `User` config in the same way it handles other configurations, say the `Device` config. This results in the device owner being updated each time a key is pressed, meaning the device will restart. I'll hopefully have a working PR up in a bit.

**Comment by ajmcquilkin** [comment]
This seems to have been resolved with the new web UI version, will be closing the PR as resolved unless anyone is still experiencing the issue.
