### ISSUE TITLE
[Bug]: Save Button Missing for Channel Editor

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/web#89]
When creating/editing a channel, there is no save button in the top right as with other configuration pages.

**Comment by rcarteraz** [comment]
@sachaw I see there's a submit button now at the bottom, however, pressing that does nothing. Additionally, in the channel editor when configuring a channel it says the page is "Bluetooth Settings". 
<img width="1315" alt="Screenshot 2023-02-23 at 9 35 59 AM" src="https://user-images.githubusercontent.com/6912600/220971828-6ac91b74-f605-425d-9b5f-36d55ea09178.png">

**Comment by sachaw** [comment]
This should now be fixed
