### ISSUE TITLE
[Bug]: Invisible checkbox QR Generator

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/web#90]
The checkbox to select a specific channel when generating a QR code/URL is not visible. You can still check the box, you just have to be sure to select the right spot. 
<img width="900" alt="Screenshot 2023-02-16 at 2 40 20 PM" src="https://user-images.githubusercontent.com/6912600/219493194-8aee336d-868c-4789-acde-1a439992cb8e.png">

**Comment by sachaw** [comment]
Fixed
