### ISSUE TITLE
deps install error

### ISSUE THREAD

**Issue by krasi-georgiev** [meshtastic/web#91]
pnpm i
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@buf%2Fmeshtastic_protobufs.bufbuild_es: Not Found - 404

This error happened while installing the dependencies of @meshtastic/meshtasticjs@2.0.20-1

@buf/meshtastic_protobufs.bufbuild_es is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
Progress: resolved 69, reused 67, downloaded 0, added 0

**Comment by krasi-georgiev** [comment]
even trying to just add this dependency

pnpm add @meshtastic/meshtasticjs
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@buf%2Fmeshtastic_protobufs.bufbuild_es: Not Found - 404

This error happened while installing the dependencies of @meshtastic/meshtasticjs@2.0.20-1

@buf/meshtastic_protobufs.bufbuild_es is not in the npm registry, or you have no permission to fetch it.

**Comment by krasi-georgiev** [comment]
commit 35c88b67dd951d6cd923bfa76b6a30c966324b8c

**Comment by krasi-georgiev** [comment]
last working commit 270718148af4e09fd24f82dadf2ccf74e410c147

**Comment by ajmcquilkin** [comment]
A working fix is to run the command `pnpm config set @buf:registry  https://buf.build/gen/npm/v1/`, although this doesn't solve the deeper problem. There's been a discussion around this in the Discord `#web` channel

**Comment by krasi-georgiev** [comment]
ok thanks
