### ISSUE TITLE
Development waypoint sending included in web build

### ISSUE THREAD

**Issue by ajmcquilkin** [meshtastic/web#93]
Not sure if this was intended to be left in the development build, but waypoints are being sent on map click. [See here](https://github.com/meshtastic/web/blob/0894fd76f507924ff681beac91d1d911ebe0a651/src/pages/Map.tsx#L91).

**Comment by SuyashOP-2** [comment]
can you plz elaborate

**Comment by Hunter275** [comment]
This can be closed, code has been commented out

https://github.com/meshtastic/web/blob/5fdd07ee68b14c687c71e785b517bdde18f2f910/src/pages/Map.tsx#L116-L125
