### ISSUE TITLE
[bug] Web Gui at current (25 Feb 2023) release not scrolling peers names at message page

### ISSUE THREAD

**Issue by vinloren** [meshtastic/web#95]
I tried the newly released version of https://client.meshtastic.org Web Gui and noticed a nice improvement that permits sending messages to specific peer. Unfortunately though only the few peers visible in the list of the message page could be reached since the list cannot be scrolled and peers beyond those visible in the page are unreachable.

**Comment by sachaw** [comment]
Fixed

**Comment by vinloren** [comment]
Thanks sachaw for the fix. Now it works well..
