### ISSUE TITLE
[Bug]: Web API Channel Does Not Match Actual Channel

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/web#99]
### Category

WiFi

### Hardware

Heltec V3, Other

### Firmware Version

2.1.3

### Description

I have a LoRa channel set at channel 48, however connecting to http://meshtastic.local for a wifi-enabled ESP32 device, reports radio channel 47.  I confirmed via iphone app, and CLI that both of them report channel 48.  Tested both a Nano G1 and a Heltec v3.  Same results.

### Relevant log output

```Shell
Relevant http://meshtastic.local output:

"radio":{"frequency":913.875,"lora_channel":47}

Relevant CLI output:
"lora": { "usePreset": true, "region": "US", "hopLimit": 3, "txEnabled": true, "txPower": 20, "channelNum": 48, "sx126xRxBoostedGain": true }
```

**Comment by rcarteraz** [comment]
> ```shell
> Relevant http://meshtastic.local output:
> 
> "radio":{"frequency":913.875,"lora_channel":47}

Can you tell me how exactly you got this information? I'm going to try and recreate?

**Comment by garthvh** [comment]
I imagine that is the serial log.

Should be fixed by this https://github.com/meshtastic/firmware/pull/2361

So maybe try the latest alpha, it is a logging error your channel is correct.

**Comment by rcarteraz** [comment]
> I imagine that is the serial log.
> 
> Should be fixed by this meshtastic/firmware#2361
> 
> So maybe try the latest alpha, it is a logging error your channel is correct.

Yeah, I'm intrigued by this because I can confirm meshtastic/firmware#2361 fixed this in 2.1.3. In fact I just flashed another V3 back to this version and so far everything is showing matching and correct channel_num.

**Comment by rcarteraz** [comment]
Okay, I'm thinking this might be something specific to the local web client, maybe it's doing what the firmware was doing before the fix was put into place in how it's displaying information in the serial log. Even with 2.1.3 and using the local client, the channel_num shows the configured channel except for in the serial log.

**Comment by caveman99** [comment]
this is indeed firmware issue. There are a few stats json structs that are populated on the web endopints, and since channel number is 1 based this sends one-off... https://github.com/meshtastic/firmware/blob/9d6e1ce8e5aa39ab5eb58619eca17cef00e946a9/src/mesh/http/ContentHandler.cpp#LL648C8-L648C101

**Comment by ghostop14** [comment]
Hi guys, @rcarteraz that was just the JSON output in the web browser after connecting to the device via http:  http://meshtastic.local/json/report.

**Comment by caveman99** [comment]
next firmware release will have the fix, this can be closed.

**Comment by rcarteraz** [comment]
> next firmware release will have the fix, this can be closed.

Can confirm correct channel is being displayed in the json report now on my end. 
"radio":{"frequency":914.125,"lora_channel":49}

Cli: "channelNum": 49
